### ISSUE TITLE
question about hw instancing

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#102]
Hi Federico.

Sorry to bother you again with my technical and maybe nonsense questions.

I have been thinking in using nxz format in order to load a set of assets:ç
     SCENE.NXZ=model0, model1, model2, ..., modeln at 0 coords
My idea is to use internal color attribute as id of each model (0, 1, 2, ... , n)
By other side I will use a texture file using Uint8*3*numberOfModels array in order to know which  is the color of each model.

Until here no problem.

Now begins my question:

I have now another texture binary file (Float32Array*17*numberOfModels ) having the id and the absolute matrix of each instanced model.
0: id:model0,matrix_instance0
1:id_model0,matrix_instance1
2:id_model0,matrix_instance2
3:id_model1,matrix_instance3
4:id_model1,matrix_instance4
...
m-1:id_modeln,matrix_instancem-1
m:id_modeln,matrix_instancem

m would be the number of total instances in my scene.

Do you think would it be possible in some way to make hw instancing using the instenal color attribute (model_id) in order to instance multiple times a part of the nxz and not the full mesh?

In this way, my models can be loaded in a single file and once loaded I can use the matrix instanced texture file in order to build my scene using HW instances.

I know that is not a bug but a technical question.

Many many thanks for you support.

Best regards

**Comment by ponchio** [comment]
That's a use case I didn't really consider. The main problem is that the LOD of the instances depends on the matrix and the viewpoint. With a nexus for each model you would need to traverse all the instances, find which pieces need to be rendered, 
assemble a buffer with the matrix and make a single call, which makes sense only for a large number of  instances.

If you want both to load all the object a single file AND use instancing, you would need anyway to traverse each instance separately, in practice to treat nexus as a forest instead of a tree, with traversing etc/ separated per tree. The advantage would be not having a single file but to have a single priority queue to load objects (that otherwise would have to be managed externally).

It's a pretty big change to Nexus, moving toward an engine rather than a single model streaming.

**Comment by ua4192** [comment]
Hi Federico.

I understand.

My problem is that in my scene I have many models many times instanced like for example a single screw that instanced thousand of times. This was the reason of this use case.

Anyway many thanks for you answer.
