### ISSUE TITLE
Casting and receiving shadows with Nexus3D and Three.js

### ISSUE THREAD

**Issue by germanmitish** [cnr-isti-vclab/nexus#104]
Hi! Thank you for the amazing Nexus tools, and for Nexus + Three.js integration. The recent ES6 module was really useful - I was able to easily integrate some huge laser-scanned and 3d modeled scenes in my react app together with pmndrs/react-three-fiber lib. However, what I wasn't able to figure out, is how to enable shadow casting/receiving on the Nexus objects? I tried it on your gargoyle example but unfortunately had no success. Is that something that could be configured at the moment, or is it on the project roadway? Thank you for your response in advance! 
![image](https://user-images.githubusercontent.com/42450658/111865287-d8b3c500-896e-11eb-97af-2cd4e0bac493.png)

**Comment by ponchio** [comment]
I have commited a new version where shadows are supported, (and index.js tests shadows).
It's a temporary version line 147 of Nexus3D.js controls wether the nexus model casts shadows (still need to test receiving), will clean up soon.

I had to override a function in WebGLRenderer, since there is no clean way to inject multiple buffer rendering in Threejs.

A clean solution would be to create a Mesh for  each patch of the multiresolution structure, but I tested it and the performances are much much worse (many useless opengl calls).

**Comment by germanmitish** [comment]
Thanks for such a quick reply, that's great that the shadows can be enabled either way! Somehow I didn't manage to run updated index.js (it starts but I can see no models), but I will wait till the cleaned-up version is ready and try to learn your code better in the meantime.

**Comment by ponchio** [comment]
Cleaned up and some monkey patching done correctly.
Now the Nexus3D should behave more like a usual Mesh, where you can change material and shadow properties in the same manner.

**Comment by germanmitish** [comment]
Wow, that's incredible! Thank you so much, it works perfectly!
