### ISSUE TITLE
convert to nxs,lost the texture

### ISSUE THREAD

**Issue by yeyan00** [cnr-isti-vclab/nexus#34]
when i use nxsbuild.exe convert a obj file to nxs, it‘s ok. 
but when i use nxsview show nxs file,it lost textures.
i use meshlab open the obj file ,it can see textures. 
how can i convert it with textures?

**Comment by HunterFortuin** [comment]
When you're running `nxsbuild` is the obj, mtl, and png or jpg file all present in the directory? I found that was necessary when converting with textures.

**Comment by dragonpoint** [comment]
try this: put all files in the same directory  don't use any sub directories. you can modify the .mtl file with any text editor by yourself

**Comment by ponchio** [comment]
Can you send me a small example  so that i can find (and solve) the problem?

ponchio@gmail.com

**Comment by ponchio** [comment]
I have fixed a small bug where materials with no texture would cause problems.

Caveat: materials with no texture are not properly rendered, and due to the number of materials, the CAD models where simplification algorithm struggles, the result might be not so good.

In particular you might want to tune down the number of triangles (or the error) .

**Comment by yeyan00** [comment]
> I have fixed a small bug where materials with no texture would cause problems.
> 
> Caveat: materials with no texture are not properly rendered, and due to the number of materials, the CAD models where simplification algorithm struggles, the result might be not so good.
> 
> In particular you might want to tune down the number of triangles (or the error) .

ok, thank you very mush, i will try to  build the latest code .
