### ISSUE TITLE
loading example point cloud in chrome via three.js fails

### ISSUE THREAD

**Issue by mathib** [cnr-isti-vclab/nexus#48]
Hi! Thanks for the nice library and three.js support! I played a little bit with different sample files before moving to my own files, and I found that there seems to be an issue with viewing the `church_pointcloud.nxz`. I'm using Chrome and I received the error `ERR_CACHE_OPERATION_NOT_SUPPORTED`. It does load in an Incognito Chrome browser and Firefox. It might be something similar as the issue mentioned in https://github.com/webtorrent/webtorrent/issues/1193#issuecomment-388008037
![errors_loadingPointCloud](https://user-images.githubusercontent.com/22965460/63642165-a7ecaa80-c6bb-11e9-8781-9ea087a57c42.PNG)

**Comment by potenziani** [comment]
Hi @mathib ,
and thanks for using Nexus!

Yes, the `net::ERR_CACHE_OPERATION_NOT_SUPPORTED` message is due to a Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=770694).

However, as already mentioned here https://github.com/cnr-isti-vclab/3DHOP/issues/19#issuecomment-505063551, it is not a problem for Nexus (or for 3DHOP, if you are also using it). Indeed, when this error occurs, Nexus activates a recovery procedure, and the "Recovering geometry/texture for node ..." log message just confirm that.

**Comment by mathib** [comment]
Hi, thanks for the reply! 

Is there anything I can do, as I would like to use three.js and Nexus for viewing point clouds? At this moment, I cannot see the point cloud loading in Chrome.

The issue with Chrome seems to be from 2017 and is still not solved from there side.

**Comment by ponchio** [comment]
I suppose the visualization has a problem in Chrome,  but not in Incognito
mode, am I right?
It's not clear what the problem is apart for the error message displayed on
the console...

Could you send me a link to your test (or send the page+data)?

**Comment by mathib** [comment]
Hi Federico! Yes, it always works in Firefox and Chrome in incognito mode. Yesterday, I retried to load it right away in regular Chrome and it seems to work (I might have cleaned my cache in between, but I'm not sure anymore :p)

The test data and page was simply your `church_pointcloud.nxz` (from http://vcg.isti.cnr.it/nexus/download/Nexus_Test.zip) and the sample three.js code in this repo (https://github.com/cnr-isti-vclab/nexus/blob/master/html/threejs.html)
