### ISSUE TITLE
Nexus Three messing up with model Bounding Box

### ISSUE THREAD

**Issue by vitorkrau** [cnr-isti-vclab/nexus#53]
I converted a model from obj to nxs than I compressed. When I open this model with NXSViewer, I have no problem. My problem is when I load the model through threejs. The model load just fine but I can't fit my camera to the model because I'm having huge bounding boxes computed. For example, I have a model that has a bounding box of max size 30 (opened and calculated via MeshLab), the same model loaded in threejs has a bounding box of max size 4000. So, my function to fit the camera to the object is working but it's not fitting well since the boundingbox is 15 times larger than the model.

I can't public this model but if anyone can help me, I'm able to send the model privately.

Sorry about my English. It's not my main language.

**Comment by ponchio** [comment]
You can send me the model using this email:  ponchio@gmail.com, I will have
a look at it.

In nexus only the bounding sphere is stored (which in hindsight was a bit
stupid), the resulting bounding box  is expected to be larger than it
should be, not THAT large!

**Comment by vitorkrau** [comment]
I saw right now that I wrote 4000 instead of 400. I noted that the bounding box is larger but I couldn't find a pattern. Is there a way to know how larger the bounding box is?

In my application I need to switch between perspective and orthographic but for some reason, I can't use the same function.

**Comment by vitorkrau** [comment]
Just sent you the email with the models.

**Comment by ponchio** [comment]
It was a problem on the simplification algorithm misplacing vertices far from the model. Fixed.

**Comment by fq-selbach** [comment]
> It was a problem on the simplification algorithm misplacing vertices far from the model. Fixed.

Is this fix already included in the latest release version (4.2.2.)?
I think I have the same issue, at least nxsviewer has properly centered rotation axis but the HTML demo has an axis offset.

**Comment by potenziani** [comment]
Hi @fq-selbach 
the fix above dates back to October 3rd 2019 (https://github.com/cnr-isti-vclab/nexus/commit/2dadd10db295049e3eada27c805f001fda810f04), so it is already included in the 4.2.2 release (4 Oct 2019).

It was a little bug related to the Nexus models generation, but what you are experiencing seems to be a visualization issue (since you reported different behaviors in different viewers rendering the same dataset). So, most probably the issue is related to the threejs examples provides with the Nexus package, that only serve as demonstrators, so are quite raw (unlike 3DHOP, that is a maintained framework).

I just committed a cleaned and updated version of these examples, please try with that.

**Comment by fq-selbach** [comment]
It works :-)
I think changing `nexus_obj.position.set(p.x*s, p.y*s, p.y*s);` to `nexus_obj.position.set(p.x*s, p.y*s, p.z*s);` did the trick. I only just noticed that p.y is used twice in the old version ^^.

I've also created a pull request in case you want to update your three.js lib to r110 (currently their CDN version): https://github.com/cnr-isti-vclab/nexus/pull/77

**Comment by ponchio** [comment]
Thanks, merged. :)
