### ISSUE TITLE
Disposing models on three js

### ISSUE THREAD

**Issue by vitorkrau** [cnr-isti-vclab/nexus#55]
I tried everything to dispose the mesh but my RAM goes down 1mb at maximum. I know that when I don't add the mesh to the scene, the page takes up 4mb of RAM. When the mesh is loaded, the same page takes up 25mb of RAM. I'm running this function to dispose things but it seems it's not working.

`
function remove(){

			scene.traverse(function(o){
				if (o.geometry) {
					o.geometry.dispose();             
				}

				if (o.material) {
					if (o.material.length) {
						for (let i = 0; i < o.material.length; ++i) {
							o.material[i].dispose();              
						}
					}
					else {
						o.material.dispose();
					}
				}
			});			

			renderer && renderer.renderLists.dispose();
			renderer && renderer.dispose(); 
			stopAnimate();
			
			renderer.domElement.parentElement.removeChild(renderer.domElement)			
			window.removeEventListener('resize', onWindowResize, false);
			window.removeEventListener('keydown', resetCamera, false);
			scene = null;
			camera = null;
			renderer = null;
			nexus_obj = model = null;
			pCamera = oCamera = null;
			controls = null;
	
		}
	`

Any help?

**Comment by ponchio** [comment]
Hi, I totally neglected the problem!

Anyway I implemented a .dispose() method of NexusObj that removes the mesh,
clear the geometry and the opengl buffers.

I fixed also a couple of memory leaks (aaarggghhhhh)
Get the nexus.js and the nexus_three.js from the repository.

It's tricky anyway to detect memory release (since the GC runs when it
feels like), but it looks like it works.
