### ISSUE TITLE
Question about texture sizes [not an issue]

### ISSUE THREAD

**Issue by kyavichev** [cnr-isti-vclab/nexus#59]
I am using your product (nexus) and I noticed a lot of shimmer while rendering on the client. I dug into the code and figured out that the textures nexus creates are not power of 2. I changed it so that textures are always power of 2 and I was able to turn on mipmaps on the client. So, my question is: what was the reasoning behind this choice? The only downside to forcing textures to be a power of 2 is that they are slightly larger, but with JPG compression, that should be negligible. Would you mind sharing why you guys made this choice and is there something I am missing?

If there are no reasons why we can't force pow of 2, ill make a patch.

Thanks!

**Comment by ponchio** [comment]
While jpeg compression makes additional larger disk and transfer space negligible, it's not true for GPU memory (up to 4 times the size!).

We might want to compromise by allowing a small number of mipmaps (say 3, forcing the size of the mesh to be multiple of 8). The reasoning behind is that we would rarely  (if ever) use higher mipmaps since the nexus would use different patches, assuming computations were right.

An alternative would be to leave an option in construction to force power of 2 textures....

**Comment by kyavichev** [comment]
I have a PR open - if an argument 'k' specified, then output texture size will be nearest larger power of 2: https://github.com/cnr-isti-vclab/nexus/pull/62
