### ISSUE TITLE
nxsbuild  issue when converting a ply file

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#68]
Hi.

When I try to convert a simple ply file I get this error:

> Reading test.ply
> Components: mesh colors
> Normals enabled
> Colors enabled
> Creating level 0
> Fatal error: Quantiziation is too severe!
> The bounding box is far from the origin (with respect to its size),
> The model might be quantized.
> Try to move the model closer to the origin using -T or -G

It seems that the bounding box info is wrong but I cannot see the problem.

I can open this ply file without any problem.

[test.zip](https://github.com/cnr-isti-vclab/nexus/files/3957005/test.zip)

Best regards

**Comment by ponchio** [comment]
I have added a heuristic to detect 3d models in geographic coordinates
(usually double precision).
Since nexus uses 32 bit floats to save space (and since rendering only
support 32 bit floats),
the conversion will severely quantize the model.
I suggest to the user to center the model in the origin (or ask nxsbuild to
do that -T or -G).

In your case, for such a small model the heuristic is probably just plain
wrong. I will try to fix it, sorry and thanks for the sample.

**Comment by ponchio** [comment]
Fixed the heuristic.
