### ISSUE TITLE
Invalid args passed in to isVisible in js implementation

### ISSUE THREAD

**Issue by andresubiquity6** [cnr-isti-vclab/nexus#69]
in html/js/nexus.js:

line: 739: if (!t.isVisible(cx, cy. cz, spheres[off+4]))

should be: 
if (!t.isVisible(cx, cy, cz, r))
or
if (!t.isVisible(cx, cy, cz, spheres[off+4])))

I'll let you advise on the correct value for 'r' - but the fix to replace '.' for ',' is necessary.

**Comment by ponchio** [comment]
I should increase the font size as I am getting old.

About the decision of using the shpere radius or the tight one:

The sphere radius must be large enough so that the sphere includes all the spheres of the children nodes. This ensures that the error of a parent is never lower than the error of the children.

If we use the tight sphere this might happen and some node that should be refined wont be. How likely this will be and how noticeable?

On the other hand the culling will be much more aggressive with the tight radius.

I need some testing (leaving the tight radius for now).

Thanks for spotting the bug (how?)

**Comment by andresubiquity6** [comment]
Thanks for the quick reply and the clarification regarding the correct bounds selected.  As for the bug, ran into it while I was playing around with adding an additional layer of culling to the system.

I was actually a little surprised to find that js doesn't throw an exception on that code.

Cheers!
