### ISSUE TITLE
How to prevent freezes and framerate drops while loading the several patches of the nxs/nxz file?

### ISSUE THREAD

**Issue by Albanbrice** [cnr-isti-vclab/nexus#78]
Hello, 
I managed to load a quite big nxz (400MB) file alongside a pointcloud mixing potree 1.7 (three.js R109) and nexus, which renders quite well in the end, apart some UV errors here and there.
But my concern is that while the several patches are loading, there are some drastic framerate drops that happen to slow or freeze the mouse events (rotation over the 3D object, etc), which is a bit frustrating..

Is there a way to fix this? I tried also with a recent revision of three.js (R118).

My bet is that I'd have to tweak some async function, but what and where?

Here the example on line (the javascript is embedded in the last <script> tag) .

http://www.archeo3d.net/projets/Charriere/choeur_model.html

Thanks in advance, any help appreciated!

**Comment by ponchio** [comment]
I had a look at the data, and the culprit is the size of the texture of
the patches: they range between 1MB and 1.6MB.

Texture loading is done on the same thread (I don't think it's possible to
do otherwise in webgl) and stalls the pipeline.

What can we do (except resize the texture, which would defeat the purpose).

1)  reduce the size of the patches ( -f 5000 for example, default is 32K)
   this works up to a certain point, especially when there is very little
geometry and a lot of texture. Fragmentation in the parametrization affects
simplification and it becomes a worse proble.

2) Don't excessively simplify geometry. It looks like this dataset has been
optimized to minimize the number of triangles. Here the amount of
geometry per patch is 50KB and 1.5MB of texture.
Less aggressive simplification would result in better models and won't
impact much on rendering performances or size of the dataset.
This allows to have more patches and thus smaller textures.

3) Hope that I find enough time to rewrite the parametrization between
levels so that I can solve most of the simplification problems and  work
better with very little geometry and
fragmented parametrizations. (it's a pretty hard problem).

Ciao,
Federico

**Comment by Albanbrice** [comment]
Thanks for the answer and the tips.
The final model is already quite edited (it's a merge of two photogrammetric models), so I tried your workaround on only one component, and the result is pretty good :  

http://www.archeo3d.net/projets/Charriere/choeur_model_v2.html

The textures have more or less the same level of detail, but the core model is itself more defined, with a -f 5000.

Thanks for the good work!
