### ISSUE TITLE
some questions:

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#81]
Hi Federico.

I found these settings on nexus.js library:
```
var targetError   = 2.0;    //error won't go lower than this if we reach it
var maxError      = 15;     //error won't go over this even if fps is low
var minFps        = 2;
var maxPending    = 5;
var maxBlocked    = 5;
var maxReqAttempt = 3;
var maxCacheSize  = 512*(1<<20); //TODO DEBUG
var drawBudget    = 10*(1<<20);
```

Is there any documentation in order to know how to tune these settings to suite my scene?

Another tquestion I have is if there is any way to know how to know when the scene finish to load, I mean when there are no more pending onUpdate events.

I have also realized that there some attributes of the bufferGeomtry inside nexusObject that are not working as expected, I gues due to internal staructure of this bufferGeometry object like for example geometry.setDrawRange that is not working at all.

And finally, when I load multiple nexusObjects in my scene I have realized that sometimes if I zoom to a specific mesh after zoomin out out to the full scene some objects are not visible anymore, I guess that maybe I am reaching to the limit of my memory. Is there any workarround to force that the scene will be automatically recomputed and force to render all meshes that should be visible? I was thinking in order to order the meshes by the boxsize and distance from Camera position and use nexusObject.renderOrder in order to force this but not sure if it's an option or not.

Other thing is that when loading multiple nexusObjects in my scene I see that in each NexusObject.instance.context.meshes I see all meses duplicated instead of the mesh that makes reference to the NexuObject

Here an example with 2 nexusObjects in my scene:

```
scene.children[0].geometry.instance.context.meshes
(2) [Mesh, Mesh]
0: Mesh {reqAttempt: 0, url: "/NXZ/M5727000100400_008862105699f13d7df70237c566f19c.nxz", version: 2, verticesCount: 324291, onLoad: ƒ, …}
1: Mesh {reqAttempt: 0, url: "/NXZ/M5727000100500_e315eebeca0e927b90720868b0e96563.nxz", version: 2, verticesCount: 322905, onLoad: ƒ, …}
length: 2

scene.children[1].geometry.instance.context.meshes
(2) [Mesh, Mesh]
0: Mesh {reqAttempt: 0, url: "/NXZ/M5727000100400_008862105699f13d7df70237c566f19c.nxz", version: 2, verticesCount: 324291, onLoad: ƒ, …}
1: Mesh {reqAttempt: 0, url: "/NXZ/M5727000100500_e315eebeca0e927b90720868b0e96563.nxz", version: 2, verticesCount: 322905, onLoad: ƒ, …}
length: 2
```

Sorry for having opening an incident with so many questions that are not related at all.

Many thanks in advanced.

**Comment by ponchio** [comment]
Hi Alex, 
          you are right, those parameters are not documented. 

### targetError
The model is composed by a multiresolution pyramid of patches. Each patch is assigned a geometric error, which 
represent how close each patch is to the original model (in world unit).
This error is projected in onscreen and then expressed in pixels.
The goal of the rendering algorithm is to  collect the patches that, when the error is projected on screen is as close as possible to this value.
For non textured models the error is computed as the average of the edges length (assuming it will be rendered with color per pixel), while for textured models is  the average of the pixel size. There is some room to improves this euristic.
Empirically lower than 2 pixels on screen meas we are rendering each triangle in its own pixel.
This error is a target, that might not be reached due to other limitations.

### minFps and maxError
If non zero, and the current fps goes lower than this value, the library will change the error target (keeping between targetError and maxError) to increase the performances. maxError ensure that albeit with lower fps a certain quality is reached.

###  maxPending    
Maximum number of concurrent xmlhttprequests active. For some server it might be necessary to decrease this number if requests get stalled.

### maxBlocked   
How far the tree needs to be explored beyond the available data, in other terms how much prefetching the algorithm should do.
Higher means that more nodes will be downloaded (and possibly not used), and reactivity to changes in camera will be slower. (depends on maxPending too..)

### maxReqAttempt 
Requests to server can fail ffor a number of reasons. After a certain number of fails, we just give up.

### maxCacheSize 
How much cache (in RAM) will be used for models. It's a bit tricky to get the correct value and makes sense for very large models and fast connections. It might constrain the max resolution of the model.

### drawBudget  
Max number rendered triangles per frame. Again, it might constrains the max resolution of the model.

**Comment by ponchio** [comment]
> is any way to know how to know when the scene finish to load

Depending on the maxCache size, the scene might not be fully loaded, so I don't think it's a question that can be answered.
A more sensible question is: for this camera do the algorithm reached the requested resolution and no more nodes will be downloaded? If not a redraw will be scheduled (usually using the onUpdate event), otherwise it wont.

You can look at the context.pending variable which tells you if there are any other pending requests. (it's per context, not per model).

**Comment by ponchio** [comment]
>  some attributes of the bufferGeomtry inside nexusObject that are not working as expected,

At the moment the threejs implementation is a horrible hack. I create some fake geometry and using the onAfterRendering callback I do the real drawing. This was done for perfomance reasons, and Threejs has made available more efficient ways to work with adding and removing geometry so this will change in the future, And the god of computer science will be less pissed.

**Comment by ponchio** [comment]
> if I zoom to a specific mesh after zoomin out out to the full scene some objects are not visible anymore

This is probably a cache issue, if you can provide a sample so that I can easily replicate the issue I would gladly investigate the matter. (It might depend on a specific set of conditions: number of models, position of the models, parameters etc.).

**Comment by ponchio** [comment]
>  I see that in each NexusObject.instance.context.meshes I see all meses duplicated instead of the mesh that makes reference to the NexuObject

Actually the context should be shared among the NexusObjecs, so those should be references, not actually duplicated meshes.

**Comment by ua4192** [comment]
Many many thanks for the information.

I will try to tune my scene using these params.

About the other questions now I understand.

Best regards
