### ISSUE TITLE
Issue with ply with uv attribute

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#96]
Hi Federico.

I have the following ply file wihich contains  uv attribute:

[test.zip](https://github.com/cnr-isti-vclab/nexus/files/5728861/test.zip)

If I open the ply file I can see the uv attribute with correct values.

I use the following commands to convert the ply to nxz:
```
nxsbuild.exe test.ply -o test.nxs -C -n  -p -q 100
nxsedit.exe -z -C 8 -Y 8 -A 8 -T 8 test.nxs -o test.nxz
```

My problem is that it seems that when I open the nxz file the uv attribute is no recognized so I have no values.

Best regards

**Comment by ponchio** [comment]
I have never encountered a  point cloud with texture coordinates, so support for s and t properties in ply was never implemented.

Now the .nxs holds the texture coordinates, it should work, but I have not properly tested the pipeline.

**Comment by ua4192** [comment]
Many thanks Federico, it works.
One more question. Would it be possible to suport to add support for an external texture datatexture to be integrated in nxsbuild nxsedit conversion pipeline?

The advantage of using datatexture is that there is no need to have a value for each vertex saving space.

Best regards.

**Comment by ponchio** [comment]
If I understood correctly a data texture replaces an image with a binary array where the data is in raw format.
I am aware of two different usages: 1 is to use floating point data and 2 is to use GPU compressed textures.
The first problem is that obj, ply, and gltf don't really support any of those, the main problem is that we need to specify the format
in some way.
Alternatively 1 or more textures could be passed by command line to nxsbuild together with a format specification.

If you can provide me a sample I will implement the command line option.

**Comment by ua4192** [comment]
Hi Federico.

Here the way how  I am currently saving te texture data information in binary format:

First I generate the data using a typedArray and after I use this function in order to save this information to a file.

```
function saveTypedToFile(fileName, typedArray) {
    var buf2 = new Uint8Array(typedArray.buffer)
    fs.writeFile(fileName, buf2, 'utf8', function (err) {
	if (err) {
		return console.error(err);
	}
    });
}
```

The idea is very simple. When  generate the ply file, I use the color attribute in order to codify the id of each vertex. In my ply files I have many parts forming an assembly.
Then I use the the binary file to allocate information of each part, for instance the real color, and other attributes like visibility, pickability, etc.

Until now I am using a texture load function in order to generate the DataTexture at nxz loading time at onNexusLoad()  function.
By now I am using Uint8Array type array texture.

```
function load_binary_resource(url) {
	var byteArray = [];
	var req = new XMLHttpRequest();
	req.open('GET', url, false);
	req.overrideMimeType('text\/plain; charset=x-user-defined');
	req.send(null);
	if (req.status != 200) return byteArray;
	for (var i = 0; i < req.responseText.length; ++i) {
		byteArray.push(req.responseText.charCodeAt(i) & 0xff)
	}
	var buf = Uint8Array.from( byteArray).buffer;
	var u8 = new Uint8Array(buf);
	return u8
}
```

The advantage against using uv internal vertext texture coords is that for example I can have an assembly (nxz file) that can contains 5M of vertices but only 100 different parts inside and my texture only will contain 100 values (one for each part instead one for each vertex saving a lot of space)

Then I am ready to use these attributes in my custom shader.

The problem is that I have to load 2 different files for each nxz file.

Best regards

**Comment by ponchio** [comment]
Hi Alex, 

The main concern seems to be that you need to download an additional file when loading nxz: since nxz is loaded in chunks, it doesn't really make any difference in term of performance or bandwidth, it would just be more convenient to have the texture with the data embedded in nxz as you would have to deal with a single file in storage.

I could easily store a texture into nxz pointcloud, and probably refer all of the vertices of the different levels of the nxz to the same texture (that is a feature I actually plan to develop).

You would like to store a custom dataTexture instead of an image, and here I have the problem where we need to TELL nxsbuild that this texture is just a data blob, width and height. (a command line option would work), but I would have to significantly rewrite the texture management).

Even more difficult would be to  tell THREE.js how to render this texture, since DataTexture have a limited set of formats (if I understood correctly), and your data seems to be pretty custom.
